name: Scala CI and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensures Git history is available for sbt-git

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.402+6'
        distribution: 'temurin'

    - name: Cache sbt
      uses: actions/cache@v3
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
        restore-keys: ${{ runner.os }}-sbt-

    - name: Build with sbt
      run: sbt package

    - name: Extract tag name
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Determine JAR file name
      run: echo "JAR_NAME=caseclassbuilder_2.12-${{ env.TAG_NAME }}.jar" >> $GITHUB_ENV

    - name: List JAR files
      run: ls -l ./target/scala-2.12/

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.TAG_NAME }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/scala-2.12/${{ env.JAR_NAME }}
        asset_name: ${{ env.JAR_NAME }}
        asset_content_type: application/java-archive
